### ISSUE TITLE
Non banned users can submit appeals

### ISSUE THREAD

**Issue by OviiiOne** [jcsumlin/discord-ban-appeal#10]
**Did you follow the steps outline in the README?**
- [x] Yes I did

**Describe the bug**
I followed the steps and I made sure I didn't set the skip ban check variable to true, even though, non-banned users can submit appeals.

**To Reproduce**
1. Deploy the site on netlify and fill all the variables
2. Make sure the skip ban check variable is not set to "true"
3. Submit an appeal with an unbanned user
4. Appeal will go through

**Expected behavior**
Appeal will not be sent (and user will be told he is not banned)

**Screenshots**
None that can make it clearer.

**Desktop (please complete the following information):**
 - Browser Vivaldi
 - Version 4.1.2369.21

**Comment by jcsumlin** [comment]
Thanks for reporting this! I will investigate this later today

**Comment by jcsumlin** [comment]
Fixed in #11
