### ISSUE TITLE
No icon and incorrect site title

### ISSUE THREAD

**Issue by OviiiOne** [jcsumlin/discord-ban-appeal#17]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**
No icon appears on the page, on it's place there's only a text that says "undefined Discord icon".
Instead of the set description and title the page reads: Discord Ban Appeal System

**To Reproduce**
1. Set a description and add your server id to the variables
2. Save changes and deploy
3. Go to your page

**Expected behavior**
You can see the icon and the set description.

**Screenshots**
https://i.imgur.com/j71rd38.png

**Desktop (please complete the following information):**
 - Browser: Opera GX
 - Version: LVL 3 (core: 82.0.4227.50)

**Additional context**
The server banner is a GIF in case that's the problem, but IIRC it didn't work with a static png.

**Comment by jcsumlin** [comment]
I haven't actually been able to test with a server that has a gif icon so that could very well be an issue. Can you provide a SAFE screenshot of your environment variables so I can check those?

Also are you able to log in or does that error out as well?

**Comment by OviiiOne** [comment]
Here are my env variables: [https://i.imgur.com/ByxgjsL.png](url), [https://i.imgur.com/ByxgjsL.png](url).

I can log in, though I can log in with banned and non-banned accounts.

And when I try to submit the application the website throws the following error: "There was an problem sending your request to the set discord webhook. Please contact an admin or open a support ticket"

**Comment by jcsumlin** [comment]
Thanks for this.
Quick checklist before we continue with more support:

- [ ] When did you fork the project? 
- [ ] Have you made any Pull requests to your repo to update it recently?
- [ ] Is the bot that you created present in your server (is it online or offline)?
- [ ] Does it have permissions to manage banned users? What permissions does it have?
- [ ] Are you familiar with browser DevTools? If so could you open up the network tab and run through the process of logging in, filling out the form, and submitting it? I want you to look for any requests that show up in the red text. That will indicate a request that failed and hopefully give me more information on what is breaking.

**Comment by OviiiOne** [comment]
- I forked the project before September 1st, I opened an issue back then because non-banned users could submit appeals. It was fixed in #11.
- I made a pull request to keep it up to date yesterday iirc because I saw the email functionality and the deny and block users function.
- I'm using the same bot I use for Sylveon's appeal bot, it's never been online, afaik that's the usual behaviour because it's not hosted.
- It does have ban permissions.
- I did the DevTools thingy and this is what came out, hope it's what you're looking for: https://i.imgur.com/JtU3tZA.png

**Comment by jcsumlin** [comment]
Thanks for clearing that up for me, would you mind joining the support server? 
I think I see what's going on. There is a request that gets the guild information and that returns the icon hash which is then used to create the source URL for the icon image. 
`https://cdn.discordapp.com/icons/${process.env.REACT_APP_GUILD_ID}/${response.data.guild_icon}.png`
since that icon is a gif and not a png it's not able to construct the proper URL so you can see it's trying to fetch `undefined.png`

**Comment by OviiiOne** [comment]
Not a problem, already joined ^^

**Comment by jcsumlin** [comment]
So we were able to solve this issue, nothing changed code-wise, just needed to double-check the environment variables and redeploy in netlify. I think it would be a good idea to add support for animated server icons based on the `features` array that is returned from the `/guilds/{id}` endpoint.
