### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function after logging via discord on /callback endpoint

### ISSUE THREAD

**Issue by FatGrizzly** [jcsumlin/discord-ban-appeal#18]
**Did you follow the steps outline in the README?**
- [*] Yes I did
- [ ] No, I found them confusing

**Describe the bug**
Hello!
I logged into the Ban Appeal form, but after authentication, it redirects to a gray page(/callback?codexxxxxxxxxxxxxxxxx), and when I open my browser console I see this 
"TypeError: Error.captureStackTrace is not a function"

**To Reproduce**
1. Go to 'ban-appeals.infinitzhost.com/'
2. Click on 'Login'
3. open browser console

**Expected behavior**
I should be logged in and should be able to fill form.

**Screenshots**
![image](https://user-images.githubusercontent.com/66728880/149648096-2f261e23-7882-4de6-8701-c47acda6367a.png)

**Desktop (please complete the following information):**
 - Firefox
 - 95.2

**Comment by jcsumlin** [comment]
Your sitw works for me, please make sure you don't have any extensions that might interfere with cookies

**Comment by nooksmr** [comment]
Hello.

I have the exact same issue with Firefox 110.0 / Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0.
```
Uncaught TypeError: Error.captureStackTrace is not a function
    value RequestHandler.js:84
    value oauth.js:91
    value Callback.js:14
    React 2
        os
        hu
    unstable_runWithPriority scheduler.production.min.js:19
    React 9
        Fi
        du
        Qs
        Gs
        Lu
        Fu
        tu
        Fu
        render
    398 index.js:12
    a callback:1
    215 main.126a8dae.chunk.js:1
    a callback:1
    t callback:1
    r callback:1
    <anonymous> main.126a8dae.chunk.js:1
RequestHandler.js:84:8
```

Chromium-based browsers load the page and connect, i guess (i have another issue), but i report this one here, as I think Firefox isn't compatible.

King regards,
