### ISSUE TITLE
Discord logo renewal/refresh

### ISSUE THREAD

**Issue by docimin** [jcsumlin/discord-ban-appeal#23]
**Is your feature request related to a problem? Please describe.**
No, just a little change.

**Describe the solution you'd like**
Refresh the discord logo (New logo, you still use the old one)

**Describe alternatives you've considered**
None

**Additional context**
[Please see there for branding](https://discord.com/branding)

**Comment by jcsumlin** [comment]
Thanks for the suggestion! You are right I need to update the discord branding
