### ISSUE TITLE
Discord ban

### ISSUE THREAD

**Issue by johnwayne690** [jcsumlin/discord-ban-appeal#33]
Hi,
I am asking for help. For many months, I have been building my wallet and reputation on the zksync network and its discord. By completing tasks, testing the network and collecting nft, all this can be wasted. Two days ago, during the application for zk success rookie, which I received I left my 8-year-old son with the computer turned on. After returning, I noticed that the zksync server had disappeared from my discord. When I asked my son what happened, he replied that he wanted to help me get another badge and entered something. I contacted the zksync support but I did not receive an answer. I don't know. where should I look for help and I am devastated. Please help.
My discord id is johnwayne2518 and nick is John Wayne.

Thank you in advance for your help.

**Comment by MrFoxyOfficial** [comment]
Hey buddy. 

This github wont be able to get you into the server ot unban you. 

Thry have 0 control over the server and actions within  it. You're better off trying to reach zksync, than here. Trust me.

This is just a software, where you can setup a ban appeal process for your own server, not for something thats irrelevant to the software. Sorry.

**Comment by johnwayne690** [comment]
Hi,
Thank you for your answer. I tried to file an appeal on the zksync discord
ban appeal website and there I received a message, the screenshot of which
is attached. I really don't know where to look for help anymore.

pt., 23 lut 2024, 22:32 użytkownik Rok Vrečar Švajger <
***@***.***> napisał:

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
