### ISSUE TITLE
cant submit

### ISSUE THREAD

**Issue by suhair01** [jcsumlin/discord-ban-appeal#34]
**Did you follow the steps outline in the README?**
- [ ] Yes I did
- [ ] No, I found them confusing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by suhair01** [comment]
i cant submit the appeal

**Comment by suhair01** [comment]
![image](https://github.com/jcsumlin/discord-ban-appeal/assets/118732317/fee1dd63-b177-49ee-9504-0230d10b1c3a)

**Comment by MrFoxyOfficial** [comment]
Thats an issue on zksync side, not jcsmulin.

**Comment by suhair01** [comment]
what i can do now?

**Comment by MrFoxyOfficial** [comment]
Try and keep reaching out to them. Nothing else that you can do.
