### ISSUE TITLE
Please Unban my discord

### ISSUE THREAD

**Issue by xRecodz** [jcsumlin/discord-ban-appeal#35]
I've tried filling out the form here https://appeal.zksync.dev/form

However, when I clicked "submit", there was a notification to continue on GitHub, so I did it here.

Q: Why do you think you were you banned?
A : I don't know, im really forgot

Q: Why do you feel you should be unbanned?
A: because I will contribute to zksync, I am also a user (zksync community), I interact a lot in the zksync ecosystem

Q: What will you do to avoid being banned in the future?
A: I promise to maintain zksync's good name, I will also maintain my actions in the future.

please unban my discord account.

**Comment by xRecodz** [comment]
i've trying many time to join, but

"error unable to invite"

i've try to change my ip, but doesnt work.

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
