### ISSUE TITLE
Discord被禁用访问ZKSync频道

### ISSUE THREAD

**Issue by MandalaSigit** [jcsumlin/discord-ban-appeal#36]
**Did you follow the steps outline in the README?**
- [x] Yes I did

我是来自中国的用户因为需要使用VPN导致我的IP不稳定，可能是这个原因造成我被禁止。

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
