### ISSUE TITLE
Discord BAN

### ISSUE THREAD

**Issue by VadSsS** [jcsumlin/discord-ban-appeal#37]
![Знімок екрана 2024-02-25 103542](https://github.com/jcsumlin/discord-ban-appeal/assets/103873512/659b4ad4-d90e-4130-80cd-24a54b42fd5e)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
