### ISSUE TITLE
Zksync unbanned 

### ISSUE THREAD

**Issue by 0xsheg** [jcsumlin/discord-ban-appeal#38]
My account was hacked from a sever that was sending the links unknowingly to me, I got to know I've be banned from servers this morning after the constant spamming. I've never and would never send sever links on my discord. Please help restore me to serve, I've been an active member unchain and also get some info's on the servers as well. And also need access to libertas Ominbus channel. 

Regards 
SHEGZ

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
