### ISSUE TITLE
discord zksync appeal

### ISSUE THREAD

**Issue by johnwayne690** [jcsumlin/discord-ban-appeal#39]
When I try to submit an application to have the ban lifted on the zsync discord ban appeal website, the message I added in the attachment appears. In addition, the next message is about an incorrect captcha code. It is not possible to submit an application. Please help.
![Zrzut ekranu 2024-02-23 173534](https://github.com/jcsumlin/discord-ban-appeal/assets/137923931/f52cb981-2123-4031-8fcb-8d739a16d32c)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
