### ISSUE TITLE
Failed to post

### ISSUE THREAD

**Issue by Lualau** [jcsumlin/discord-ban-appeal#40]
**Did you follow the steps outline in the README?**
- [X] Yes I did
- [ ] No, I found them confusing

**Describe the bug**
I filled out the form, completed the captcha, but the form is not sent.

![image](https://github.com/jcsumlin/discord-ban-appeal/assets/96830647/80fa6f14-9df5-4b87-9c76-82bc8723416b)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Lualau** [comment]
![image](https://github.com/jcsumlin/discord-ban-appeal/assets/96830647/19c2c981-0475-4297-ac09-b36266a15f70)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
