### ISSUE TITLE
Difficulty returning again

### ISSUE THREAD

**Issue by lilRaj** [jcsumlin/discord-ban-appeal#41]
Hi sir . I was in your community for several months but left for a while. It's been more than a few months since I left and I can't re-enter the community today
![Screenshot_20240226_033419_Kiwi Browser](https://github.com/jcsumlin/discord-ban-appeal/assets/159702910/3ea4be23-4d75-48d7-be04-9b557c3d1fc4)
![Screenshot_20240226_024105_Kiwi Browser](https://github.com/jcsumlin/discord-ban-appeal/assets/159702910/dcb77e97-b34a-4ee9-91bb-621e427971ea)
![Screenshot_20240211_182252_Discord](https://github.com/jcsumlin/discord-ban-appeal/assets/159702910/c3d1296f-c7ca-4a44-a7b3-6c402897cf64)
![Screenshot_20240211_182303_Discord](https://github.com/jcsumlin/discord-ban-appeal/assets/159702910/9206740d-a28d-49f5-84da-b45f59e45892)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github. 

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
