### ISSUE TITLE
Discord unbanned

### ISSUE THREAD

**Issue by suwanan0933** [jcsumlin/discord-ban-appeal#44]
I didn't do anything wrong, maybe because I sent HI on general discord at that time

I have been following zksync for a long time in contributing, and I have had NFT Libertas for a long time, I want to claim that role

I promise I won't say dirty words or just say Hi, which will get me blocked again, I promise not to repeat the mistake again, please help me sir

MY Discord: esupport#0

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
