### ISSUE TITLE
I can't join the zksync era discord channel

### ISSUE THREAD

**Issue by riz82** [jcsumlin/discord-ban-appeal#45]
**Did you follow the steps outline in the README?**
- [ ] Yes I did
![syncdc](https://github.com/jcsumlin/discord-ban-appeal/assets/50347237/1f5da02a-42a3-4a3a-80e1-d3e3ca33ee32)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![syncdc](https://github.com/jcsumlin/discord-ban-appeal/assets/50347237/369a5423-8731-47f2-aa55-9ca5b259f944)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.

**Comment by riz82** [comment]
ok thx ser.
