### ISSUE TITLE
appeal error

### ISSUE THREAD

**Issue by mdbizz** [jcsumlin/discord-ban-appeal#46]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
