### ISSUE TITLE
unable to accept invite

### ISSUE THREAD

**Issue by TOOr121** [jcsumlin/discord-ban-appeal#47]
i add to my discord name |zksync 
I'm sorry, I had no bad intentions, please unban my discord name : toor3902
thanks

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
