### ISSUE TITLE
Ban Appeal not going through

### ISSUE THREAD

**Issue by tendiesman** [jcsumlin/discord-ban-appeal#48]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**
<img width="904" alt="Screenshot 2024-02-27 at 9 50 58 PM" src="https://github.com/jcsumlin/discord-ban-appeal/assets/107626690/008ed567-ec7e-4bbf-9292-d5a4035d17b8">

I got an error when trying to appeal my ban. 

The error is: "Failed to post message to appeals channel using bot token. Please contact and admin or open a ticket here https://github.com/jcsumlin/discord-ban-appeal/issues/new?template=bug_report.md"

Here are the inputs I wrote for each of the questions:

I made a joke saying ad was coming February 30th. This is not even a real date so I thought people would understand it's a joke.

I was just trying to provide some humor. I now see that it is not funny to joke about this and to instead be serious and help educate new members and the community on the great work zksync is doing.

I will not make any comments or speculation about when the airdrop might be.

My discord ID is tendiesman

**To Reproduce**
Fill out the form, do the verification, and try to submit.

**Expected behavior**
Error message will appear.
**Screenshots**
Added above.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 123
.

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
