### ISSUE TITLE
Unable to submit Discord Ban Appeal

### ISSUE THREAD

**Issue by ivanobridge** [jcsumlin/discord-ban-appeal#49]
Hi,

I'm trying to submit an appeal for my Discord Ban but failed.

Discord ID = ivanobridge#0

![Screenshot 2024-02-28 111415](https://github.com/jcsumlin/discord-ban-appeal/assets/158307110/ee847ce2-eb7a-4ce6-8571-5a518979d8e8)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
