### ISSUE TITLE
tôi bị lỗi không thể vào discord

### ISSUE THREAD

**Issue by tranhuuha** [jcsumlin/discord-ban-appeal#50]
**Did you follow the steps outline in the README?** 
- [x] Yes I did

**Describe the bug**
cannot accept the invitation

**To Reproduce**

**Expected behavior**
i want to join discor zksync

**Screenshots**
![312312321312421](https://github.com/jcsumlin/discord-ban-appeal/assets/139369269/5a189b3c-a499-4069-ab2d-cdab1205bbdb)

**Desktop (please complete the following information):**
 - Browserchrome
 - Phiên bản 121.0.6167.189 (Phiên bản Chính thức) (64 bit)

**Additional context**
cannot accept the invitation

**Comment by tranhuuha** [comment]
![image](https://github.com/jcsumlin/discord-ban-appeal/assets/139369269/2df2d4d9-a6e0-4de6-bf97-4fa8185dc6f2)

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.
