### ISSUE TITLE
Request to be unbanned from Discord 

### ISSUE THREAD

**Issue by Sahagumel** [jcsumlin/discord-ban-appeal#51]
Hello,

Please write to request to be added back to the Official discord server.

I was in the server for a long time and have been getting very useful information, but I was recently removed from the server for some reasons I am not sure of. 

Please I use your project a lot and I will need your support to get on the server to continue getting latest information regarding the project. 

Whenever I tried using the official link on the website to get back into the server i kept getting error message that "the link has expired" 
![Uploading zksync.png…]()

My username is "@s_m_danpullo"

**Comment by MrFoxyOfficial** [comment]
This has nothing to do with zkSync!! The only server this thing is affiliated, is the one on the main page of this github.

Jcsumlin can't help you. The people that used his software, didnt congifure it properly. You're wasting your time posting stuff in here.

**Comment by Sahagumel** [comment]
Sorry Man, I was redirected here, I am in the wrong place I guess
