### ISSUE TITLE
Failed to post message to appeals channel using bot token. Please contact and admin or open a ticket here https://github.com/jcsumlin/discord-ban-appeal/issues/new?template=bug_report.md

### ISSUE THREAD

**Issue by seny4ka** [jcsumlin/discord-ban-appeal#52]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by seny4ka** [comment]
Failed to post message to appeals channel using bot token. Please contact and admin or open a ticket here https://github.com/jcsumlin/discord-ban-appeal/issues/new?template=bug_report.md

**Comment by MrFoxyOfficial** [comment]
It's pointless to try and get unbanned here. The developer of this application/unban request application has **NOTHING** to do with their server. ZKSYNC** server or whatever it is didn't fully configure the application and therefore, it's showing you this link. Your best way to reach out would be through social media.
