### ISSUE TITLE
Access to discord

### ISSUE THREAD

**Issue by jjrocketnicki** [jcsumlin/discord-ban-appeal#53]
**Did you follow the steps outline in the README?**
- [ ] Yes I did
- [X] No, I found them confusing

**Describe the bug**
When I try to report access problem I get the error:

Failed to post message to appeals channel using bot token. Please contact and admin or open a ticket here https://github.com/jcsumlin/discord-ban-appeal/issues/new?template=bug_report.md

**To Reproduce**
1. Go to https://appeal.zksync.dev/form
2. Click on submit
3. See error

**Expected behavior**
Form to be sent

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [121.0.6167.185 ]

**Comment by MrFoxyOfficial** [comment]
It's pointless to try and get unbanned here. The developer of this application/unban request application has **NOTHING** to do with their server. ZKSYNC** server or whatever it is didn't fully configure the application and therefore, it's showing you this link. Your best way to reach out would be through social media.
