### ISSUE TITLE
My Discord account was hacked and you banned me for spamming

### ISSUE THREAD

**Issue by lacostq** [jcsumlin/discord-ban-appeal#54]
**Did you follow the steps outline in the README?**
- [ *] Yes I did
- [ ] No, I found them confusing

**Describe the bug**
Hello,
My Discord account was hacked and you banned me for spamming,
A hacker under my name spammed all the groups I was a member of and your chats. 
As of today I have restored my original account scroll_io, id - 663092764950396958.
The hack happened on November 8, but I didn't notice it until 5 days later.
I request you to remove my ban and restore my roles.

**To Reproduce**

**Expected behavior**
Since I have invested a lot of time in testing the project. I have more than 100 transactions on my wallet in the zkSync network, I like the concept of the zkSync project and I see how fast you are developing. I don't want "some hacker" who hacked my account to affect your opinion of me, and I don't want to be disappointed in this situation. I am confident that you will make a reasonable decision on my issue and allow me to continue communicating and participating in your project!

I have secured myself from 2fa and will be more vigilant before giving permission to connect discord on sites. Because that's probably how I got hacked.

**Screenshots**
![download](https://github.com/jcsumlin/discord-ban-appeal/assets/111874697/222d02c1-a698-400c-a0cd-3912485bf4b6)
![download](https://github.com/jcsumlin/discord-ban-appeal/assets/111874697/3b01a73e-ab02-4e4d-92c5-aafa95b73e66)

**Desktop (please complete the following information):**
 - Browser [ chrome, ]
 - Version [121.0.6167.185]

**Additional context**

**Comment by MrFoxyOfficial** [comment]
It's pointless to try and get unbanned here. The developer of this application/unban request application has **NOTHING** to do with their server. ZKSYNC** server or whatever it is didn't fully configure the application and therefore, it's showing you this link. Your best way to reach out would be through social media.
