### ISSUE TITLE
i can't create discord appeal :c

### ISSUE THREAD

**Issue by ernestodel** [jcsumlin/discord-ban-appeal#55]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ernestodel** [comment]
<img width="337" alt="qqq" src="https://github.com/jcsumlin/discord-ban-appeal/assets/161764878/4fb3fbb0-8da3-4f4a-8609-d3c59fc779cf">

**Comment by MrFoxyOfficial** [comment]
ZKSYNC server or whatever it is, didn't fully configured the application and therefor, it's showing you this link. Your best way to reach out would be through social media.
