### ISSUE TITLE
error when i hit the submit button

### ISSUE THREAD

**Issue by Pixel-Gamer** [jcsumlin/discord-ban-appeal#6]
![image_2021-05-20_200443](https://user-images.githubusercontent.com/46429473/119063240-9de9ff80-b9a6-11eb-950b-6c3e644c90f9.png)

**Comment by jcsumlin** [comment]
Can you please provide steps to reproduce this error? Have you set all your environment variables described in the readme.md?

**Comment by Pixel-Gamer** [comment]
> Can you please provide steps to reproduce this error? Have you set all your environment variables described in the readme.md?

yes i did everything right

**Comment by jcsumlin** [comment]
Closing this issuse as there has been no screenshots from user. Feel free to re open with more information.
