### ISSUE TITLE
DISCORD BANNED

### ISSUE THREAD

**Issue by bokthirnafiz02** [jcsumlin/discord-ban-appeal#60]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bokthirnafiz02** [comment]
log in with different if ...i have a laptop and my mobile where i log in my discord account ...thats why i think it is shows different ip many time ..so please unband me as sooner as possible

log in with different if ...i have a laptop and my mobile where i log in my discord account ...thats why i think it is shows different ip many time ..so please unband me as sooner as possible

i will be more carefull about banned factor ....

**Comment by MrFoxyOfficial** [comment]
It's pointless to try and get unbanned here. The developer of this application/unban request application has NOTHING to do with their server. ZKSYNC** server or whatever it is didn't fully configure the application and therefore, it's showing you this link. Your best way to reach out would be through social media.
