### ISSUE TITLE
unban request 

### ISSUE THREAD

**Issue by Pederoze1** [jcsumlin/discord-ban-appeal#68]
**Did you follow the steps outline in the README?**
- [x] Yes I did
- [ ] No, I found them confusing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Pederoze1** [comment]
My discord handle: mirakoya

I was unable to submit an appeal through form so will try to do it here

Why do you think you were you banned: i'm not sure as i didn't break any rules 

Why do you feel you should be unbanned: i have 20+ score of my gitcoin passport and would like to get discord role

What will you do to avoid being banned in the future: Do whatever it takes to avoid getting banned and do whatever it takes to make sure your bot doesn't mistake me for a bot.

Thank tou in advance and have a good day Mirako

**Comment by MrFoxyOfficial** [comment]
You might as well close the request, because ypu wont get any support here. 

This is not affiliated with zkSync in any shape or form
