### ISSUE TITLE
OAuth2 Redirect 

### ISSUE THREAD

**Issue by Albert-J04** [jcsumlin/discord-ban-appeal#7]
Do you need to provide a Redirect URL in the Discord Developers Portal?

I can't login to this without getting an Invalid redirect url warning.

**Comment by masterofninja** [comment]
Your redirect url should be https://YOURWEBSITENAME.netlify.app/callback

**Comment by jcsumlin** [comment]
Closing issue as @masterofninja has provided the answer.
